### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by prubbens** [burtonrj/CytoPy#10]
This seems like a great package (finally a full cytometry package in Python!). 

However, upon installment, both using the github repository and following the instructions via the API, I get the following conflict error between Keras and Tensorflow: 

`error: Keras-Preprocessing 1.1.0 is installed but keras-preprocessing<1.2,>=1.1.1 is required by {'tensorflow'}`

Any idea on how to resolve this?

**Comment by burtonrj** [comment]
Hi prubbens! Thanks for your comment.

I actually have a new major release coming out in the next couple of days as there was many issues with the initial design I wasn't happy about. Major changes will be detailed in the release (but there a lot since the first release). 

For the time being, I would say this issue could be down to the version of Tensorflow you're using. In the original release I was using TF v1.14. This will change in the update to TF v2.

Apologies for the inconvenience. CytoPy is still immature and evolving. 

Thanks,
Ross

**Comment by prubbens** [comment]
Great, I'll wait for the release, looking forward to it!

**Comment by burtonrj** [comment]
New release today. Check out the docs for detailed description: https://cytopy.readthedocs.io/en/latest/.

If I can generate enough interest I'm thinking of putting a youtube series up running through various examples.

**Comment by prubbens** [comment]
Great, I'll try it out this week!

**Comment by prubbens** [comment]
I'm getting a new error, again something to do with tensorflow: 

`error: numpy 1.19.0 is installed but numpy~=1.19.2 is required by {'tensorflow'}`

**Comment by burtonrj** [comment]
Hmm, this is strange. I'll bump numpy to the latest version in the requirements.txt. There is also a conda yaml file in the repo that can be used if issues persist.

I think I need to make a docker image because some of the dependencies are pretty hefty, apologies about this. Will get to work on that ASAP

**Comment by prubbens** [comment]
I've been able to install it using the .yml file, but with the addition of removing the last line `sphinx-rtd-theme==0.1.6`. 

sphinx-rtd-theme was already required earlier in the file.
