### ISSUE TITLE
Issue at installation stage

### ISSUE THREAD

**Issue by toma5692** [burtonrj/CytoPy#19]
Hi Ross, 
Thanks for all your work. I tried today to install the package. 
I followed the steps provided in the doc (using conda and installing numpy before citopy). 
I have an error related to flowutils : 
/CytoPy/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
  #warning "Using deprecated NumPy API, disable it with " \
   ^
  flowutils/logicle_c_ext/_logicle.c:120:5: error: implicit declaration of function 'hyperlog_inverse' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      hyperlog_inverse(t, w, m, a, xc, n);
      ^

When I try to install flowutils alone, it works fine. 
Do you have any ideas on what could go wrong ? A colleague of mine in the lab had the same error. 
Thanks for your help 
Thomas

**Comment by burtonrj** [comment]
Heya Thomas,

Sorry you've had issues. This might be because CytoPy isnt using the version of flowutils on pypi but rather the latest master branch at https://github.com/whitews/FlowUtils

This is because the pypi dist doesn't contain the inverse asinh and hyperlog functions. 

Leave this with me and I'll run some tests tomorrow. Flowutils is brilliant but unfortunately it requires Numpy to compile the C extensions. So you have to install Numpy first and this l can cause conflicts etc.

Some quick fixes for now: try uninstalling CytoPy, updating Numpy and then reinstalling CytoPy.

**Comment by toma5692** [comment]
Thanks Ross for the quick reply. I tried to uninstall everything but I still get the problem. I will try again tomorrow.  Keep me posted if you solve the problem tomorrow. Thanks for your help !!

**Comment by burtonrj** [comment]
No worries, I think long term I need to either:
- internalise the functionality of flowutils with my own c-bindings, or
- create a docker image with a persistent volume and setup for access to either a local or remote MongoDB server 

Note that I do have a docker image available and it's linked in the docs. But this spins up a MongoDB server within the container and doesn't persist; it's more for trying CytoPy out before committing to a local install.

Docker would probably solve the issues you're seeing so leave that with me.

**Comment by whitews** [comment]
Greetings Ross!

Came across this issue browsing around the CytoPy code. Nice work on the package! Thought I'd chime in to see if there were a way we could address this issue so you could avoid adding the FlowUtils internals to CytoPy. The issue with requiring NumPy prior to the install of FlowUtils is admittedly not ideal but was done to get the NumPy wrappers for passing arrays to C. Perhaps this warrants another look now.

Let me know if that would be of interest and we could discuss further.

Kind regards,
Scott

**Comment by burtonrj** [comment]
Hi @whitews, thanks for getting in contact. Can I just say your selection of cytometry libraries for Python made CytoPy possible, so thank you for your contribution to the field.

I agree that it makes more sense to address the issue in FlowUtils rather than ingest the code into CytoPy. I'm still very new to C and C bindings in Python but had planned to work through these notes from SciPy lectures: https://scipy-lectures.org/advanced/interfacing_with_c/interfacing_with_c.html#introduction

They note here that Cython has support for Numpy so I wonder if that is the best approach. Happy to make a pull request and start working on this.

In the meantime, anyone coming across this issue thread that is having trouble installing CytoPy and is encountering Numpy or compilation issues, please try using the Docker image: https://hub.docker.com/r/burtonrj/cytopy. I have a tutorial I'm adding to the docs soon that explains how to connect to an external MongoDB server from within the image and setup a persistent volume for HDF5 files.

**Comment by burtonrj** [comment]
New docker compose workflow is live https://github.com/burtonrj/CytoPy#quickstart-with-docker should solve most installation/dependency issues.

**Comment by toma5692** [comment]
Thks Ross !! I will have a look today ! I keep you posted !

**Comment by toma5692** [comment]
Works very well with docker

**Comment by isabella-ga** [comment]
Hi Ross, sorry to bother, I am experiencing the same issue. I was wondering if there are any updates or workarounds?

I have never used docker before (I'm a biologist!) so if there was any way I could use this with jupyter it would be great. Thanks!
